[v1]
"bat 0.24.0 (registry+https://github.com/rust-lang/crates.io-index)" = ["bat"]
"battop 0.2.4 (registry+https://github.com/rust-lang/crates.io-index)" = ["battop"]
"bend-lang 0.2.36 (registry+https://github.com/rust-lang/crates.io-index)" = ["bend"]
"cargo-update 15.0.0 (registry+https://github.com/rust-lang/crates.io-index)" = [
    "cargo-install-update",
    "cargo-install-update-config",
]
"csvlens 0.10.1 (registry+https://github.com/rust-lang/crates.io-index)" = ["csvlens"]
"difftastic 0.60.0 (registry+https://github.com/rust-lang/crates.io-index)" = ["difft"]
"fd-find 10.2.0 (registry+https://github.com/rust-lang/crates.io-index)" = ["fd"]
"ferium 4.4.1 (path+file:///home/tooster/workspace/ttr/minecraft/ferium)" = ["ferium"]
"git-delta 0.18.2 (registry+https://github.com/rust-lang/crates.io-index)" = ["delta"]
"hvm 2.0.22 (registry+https://github.com/rust-lang/crates.io-index)" = ["hvm"]
"just 1.36.0 (registry+https://github.com/rust-lang/crates.io-index)" = ["just"]
"lsd 1.1.5 (registry+https://github.com/rust-lang/crates.io-index)" = ["lsd"]
"nu 0.98.0 (registry+https://github.com/rust-lang/crates.io-index)" = ["nu"]
"ripgrep 14.1.1 (registry+https://github.com/rust-lang/crates.io-index)" = ["rg"]
"sd 1.0.0 (registry+https://github.com/rust-lang/crates.io-index)" = ["sd"]
"xsv 0.13.0 (registry+https://github.com/rust-lang/crates.io-index)" = ["xsv"]
"zellij 0.40.1 (registry+https://github.com/rust-lang/crates.io-index)" = ["zellij"]
"zoxide 0.9.6 (registry+https://github.com/rust-lang/crates.io-index)" = ["zoxide"]
